In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
#Q1
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)



[0 1 2 3 4 5]


In [7]:
#for datatype
arr.dtype

dtype('int64')

In [9]:
#Q2
arr = np.array([1.5, 2.6, 3.7])
arr.dtype



dtype('float64')

In [10]:
#yes its type is float64

In [12]:
#Q3
arr = np.array([1+2j, 3+4j, 5+6j])

arr.dtype


dtype('complex128')

In [14]:
#Q4
arr = np.array([1, 2, 3, 4, 5])
arr.dtype


dtype('int64')

In [16]:
arr_float = arr.astype(np.float32)
arr_float.dtype

dtype('float32')

In [19]:
#Q5
arr = np.array([1.123123, 2.987123, 3.456123])
arr.dtype



dtype('float64')

In [20]:

arr_float = arr.astype(np.float32)
arr_float.dtype


dtype('float32')

In [21]:
arr_float

array([1.123123, 2.987123, 3.456123], dtype=float32)

In [22]:
#Q6
def array_attributes(arr):
    size = arr.size
    shape = arr.shape
    dtype = arr.dtype
    return shape, size, dtype

In [23]:
arr = np.array([1, 2, 3, 4, 5])

In [24]:
array_attributes(arr)

((5,), 5, dtype('int64'))

In [27]:
#Q7
def array_dim (arr):
   return arr.ndim


In [29]:
arr = np.array([1, 2, 3, 4, 5])
array_dim (arr)

1

In [30]:
#Q8
def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size


In [31]:
arr = np.array([1, 2, 3, 4, 5])
item_size_info(arr)

(8, 40)

In [32]:
#Q9
def array_strides(arr):
    return arr.strides

In [35]:
arr = np.random.randint(1, 10, size=(5))
arr

array([6, 2, 8, 3, 3])

In [36]:
array_strides(arr)

(8,)

In [37]:
#Q1o
def  shape_stride_relationship(arr):
    shape = arr.shape
    strides = arr.strides
    return shape, strides


In [38]:
arr = np.random.randint(1, 10, size=(5))
arr

array([9, 5, 1, 2, 7])

In [39]:
shape_stride_relationship(arr)

((5,), (8,))

In [40]:
#Q11
def create_zeros_array(n):
    return np.zeros(n)


In [42]:
 create_zeros_array(5)

array([0., 0., 0., 0., 0.])

In [43]:
#Q12
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))


In [44]:
create_ones_matrix(5,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [45]:
create_ones_matrix(5,6).ndim

2

In [46]:
#Q13
def generate_range_array(start, stop, step):
  return np.arange(start, stop, step)

In [47]:
generate_range_array(1,10,2)

array([1, 3, 5, 7, 9])

In [48]:
#Q14
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

In [49]:
generate_linear_space(0,10,3)

array([ 0.,  5., 10.])

In [50]:
#Q15
def create_identity_matrix(n):
    return np.eye(n)

In [51]:
create_identity_matrix(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [66]:
#Q16
my_list = [1,2,3,4,5]
def numpy_array_convert(my_list):
  arr1 = np.array(my_list)
  print(arr1.dtype)

In [67]:
numpy_array_convert(my_list)

int64


In [74]:
#Q17
array1 = np.array([1, 2, 3, 4, 5,6,7,8])
array2 = array1.view()


In [75]:
array2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
array2[0] = 100

In [77]:
array2

array([100,   2,   3,   4,   5,   6,   7,   8])

In [78]:
array1

array([100,   2,   3,   4,   5,   6,   7,   8])

In [79]:
#Q18
def join_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

In [83]:
arr1 = np.random.randint(1, 10, size=(5))
arr1

array([9, 7, 5, 8, 7])

In [84]:

arr2 = np.random.randint(1, 10, size=(5))
arr2

array([4, 4, 6, 1, 3])

In [85]:
join_arrays(arr1, arr2, axis=0)

array([9, 7, 5, 8, 7, 4, 4, 6, 1, 3])

In [88]:
#Q19
arr1 = np.random.randint(1, 10, size=(3,4))
arr1

array([[2, 7, 3, 7],
       [7, 8, 4, 9],
       [6, 8, 5, 2]])

In [87]:
arr2 = np.random.randint(1, 10, size=(3,3))
arr2

array([[5, 5, 2],
       [6, 9, 3],
       [6, 3, 2]])

In [90]:
concatenated_array = np.concatenate((arr1, arr2), axis=1)
concatenated_array

array([[2, 7, 3, 7, 5, 5, 2],
       [7, 8, 4, 9, 6, 9, 3],
       [6, 8, 5, 2, 6, 3, 2]])

In [91]:
#Q20
def vertical_stack(array_list):
    return np.vstack(array_list)

In [94]:
array_list = [[1, 2, 3],[4, 5, 6,],[7,8, 9]]
vertical_stack(array_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
#Q21
def range_array(start, stop, step):
    return np.arange(start, stop + step, step)

In [98]:
range_array(0,10,2)

array([ 0,  2,  4,  6,  8, 10])

In [99]:
#Q22
def equal_space():
    return np.linspace(0, 1, 10)
equal_space()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [100]:
#Q23
def log_space():
      return np.logspace(0, 3, 5)
log_space()

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [101]:
#Q24
def create_dataframe():
    random_array = np.random.randint(1, 101, size=(5, 3))
    df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])
    return df


In [102]:
create_dataframe()

Column1  Column2  Column3
0       22       70       52
1       97       34       97
2       24       76       48
3       54       66       76
4       23       59       43

In [103]:
#Q26
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [105]:
#Q27
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

In [106]:
#Q28
arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
elements_greater_than_5 = arr[mask]
arr[mask]


array([ 8, 10,  7])

In [108]:
#Q29
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]


array([3, 4, 5, 6])

In [109]:
#Q30
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [110]:
#Q32
def filter_elements(arr, threshold):
    mask = arr > threshold
    filtered_elements = arr[mask]
    return filtered_elements

In [111]:
arr = np.random.randint(1, 10, size=(5))
arr


array([6, 4, 2, 4, 1])

In [113]:
thrshold = 2
filter_elements(arr, thrshold)

array([6, 4, 4])

In [114]:
#Q36
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
scalar = 5
result = arr + scalar

In [115]:
result

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [118]:
#Q37
arr1 = np.random.randint(1, 10, size=(1,3))
arr1

array([[5, 2, 4]])

In [119]:
arr2 = np.random.randint(1, 10, size=(3,4))
arr2


array([[4, 4, 5, 2],
       [9, 6, 6, 2],
       [2, 3, 8, 6]])

In [123]:
arr1_T = arr1.T
arr1_T

array([[5],
       [2],
       [4]])

In [124]:
arr1_T*arr2

array([[20, 20, 25, 10],
       [18, 12, 12,  4],
       [ 8, 12, 32, 24]])

In [125]:
#Q38
arr1 = np.random.randint(1, 10, size=(1,4))
arr1

array([[1, 9, 8, 7]])

In [126]:
arr2 = np.random.randint(1, 10, size=(3,4))
arr2

array([[4, 7, 9, 6],
       [3, 6, 9, 1],
       [6, 7, 3, 8]])

In [127]:
arr1 + arr2

array([[ 5, 16, 17, 13],
       [ 4, 15, 17,  8],
       [ 7, 16, 11, 15]])

In [128]:
#Q39
arr1 = np.random.randint(1, 10, size=(3,1))
arr1

array([[4],
       [4],
       [8]])

In [129]:
arr2 = np.random.randint(1, 10, size=(1,3))
arr2

array([[9, 4, 3]])

In [130]:
arr1 + arr2

array([[13,  8,  7],
       [13,  8,  7],
       [17, 12, 11]])

In [133]:
#Q41
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

In [134]:
#Q42
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr, axis =1)

array([3, 6])

In [135]:
#Q43
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
max_indices

array([1, 1, 1])

In [136]:
#Q44
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [137]:
def moving_sum(row):
    result = np.zeros_like(row)
    result[0] = row[0]
    for i in range(1, len(row)):
        result[i] = result[i-1] + row[i]
    return result

In [139]:
moving_sums = np.apply_along_axis(moving_sum, axis=1, arr=arr)
moving_sums

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [141]:
#Q45
arr = np.array([[2, 4, 6], [3, 5, 7]])
def even_columns(arr):
    all_even = np.all(arr % 2 == 0, axis=0)
    return np.all(all_even)
even_columns(arr)

False

In [143]:
#Q46
original_array = np.array([1, 2, 3, 4, 5, 6])
def reshape_array(original_array, m, n):
    reshaped_matrix = original_array.reshape((m, n))
    return reshaped_matrix



In [145]:
  reshape_array(original_array, 3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [146]:
#Q47
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(matrix):
    flattened_array = matrix.flatten()
    return flattened_array
flatten_matrix(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [152]:
#Q48
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
def join_arrays(array1, array2, axis):
    concatenated_array = np.concatenate((array1, array2), axis=axis)
    return concatenated_array
join_arrays(array1, array2 , 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [153]:
#Q49
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def split_array(array, num_splits, axis):
    sub_arrays = np.array_split(array, num_splits, axis=axis)
    return sub_arrays

In [154]:
split_array(original_array, 3, 1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [168]:
#Q51
arr1 = np.random.randint(1, 20, size=(2, 5))
arr1

array([[14, 14,  7,  4, 18],
       [ 7, 16, 11, 17,  6]])

In [167]:
arr2 = np.arange(1, 11).reshape(2, 5)
arr2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [169]:
arr1 + arr2

array([[15, 16, 10,  8, 23],
       [13, 23, 19, 26, 16]])

In [171]:
#Q52
arr1 = np.arange(10,0 , -1)
arr2 = np.arange(1, 11 )
result = arr1 - arr2
result

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [173]:
#Q53
arr1 = np.random.randint(1, 10, size=(3, 5))
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 * arr2



In [174]:
arr1

array([[1, 5, 3, 2, 3],
       [1, 3, 4, 9, 4],
       [2, 9, 3, 1, 2]])

In [175]:
arr2

array([1, 2, 3, 4, 5])

In [176]:
result

array([[ 1, 10,  9,  8, 15],
       [ 1,  6, 12, 36, 20],
       [ 2, 18,  9,  4, 10]])

In [184]:
#Q54
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
def element_wise_division():
    result = arr1 / arr2
    return result


In [185]:
arr1

array([ 2,  4,  6,  8, 10])

In [186]:
arr2

array([1, 2, 3, 4, 5])

In [187]:
element_wise_division()

array([2., 2., 2., 2., 2.])

In [188]:
#Q55
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
np.power(arr1, arr2)


array([ 1, 16, 27, 16,  5])

In [189]:
#Q56
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count_occurs(arr, substring):
    string_list = arr.tolist()
    count = sum(s.count(substring) for s in string_list)
    return count

In [190]:
substring = 'hello'
count_occurs(arr, substring)

3

In [191]:
#Q57
def uppercase_chars(arr):
    upper_chars = []
    for string in arr:
        upper_chars.extend([char for char in string if char.isupper()])
    return upper_chars

In [192]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [193]:
#Q58
def rep_substr(arr, old_substr, new_substr):
    replaced_arr = np.array([string.replace(old_substr, new_substr) for string in arr])
    return replaced_arr

In [194]:
arr = np.array(['kiwi', 'banana', 'coconut', 'apple'])
old_substr = 'banana'
new_substr = 'watermelon'
rep_substr(arr, old_substr, new_substr)

array(['kiwi', 'watermelon', 'coconut', 'apple'], dtype='<U10')

In [195]:
#Q59
def conca_strings(arr1, arr2):
    concat_arr = np.char.add(arr1, arr2)
    return concat_arr

In [196]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
arr1.astype(str)
arr2.astype(str)
conca_strings(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [197]:
#Q60
def longest_str(arr):
    lengths = np.vectorize(len)(arr)
    return np.max(lengths)


In [198]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_str(arr)

9

In [199]:
#Q61
arr = np.random.randint(1, 1001, size=100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_deviation = np.std(arr)

In [200]:
print(mean)

512.35


In [201]:
print(median)

548.5


In [202]:
print(variance)

86440.48750000002


In [203]:
print(std_deviation)

294.00763170366855


In [204]:
#Q62
arr = np.random.randint(1, 101, size=50)
perc_25 = np.percentile(arr, 25)
perc_50 = np.percentile(arr, 50)
perc_75 = np.percentile(arr, 75)


In [205]:
print(perc_25)

29.25


In [206]:

print(perc_50)

51.0


In [207]:

print(perc_75)

72.5


In [209]:
#Q63
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])
corre_matrix = np.corrcoef(arr1, arr2)
corren_coefficient = corre_matrix[0, 1]

In [210]:
print(corren_coefficient)

0.9999999999999999


In [214]:
#Q64
mat1 = np.random.rand(3, 3)
mat1

array([[0.86688476, 0.20469024, 0.66123035],
       [0.02890116, 0.9712535 , 0.7286517 ],
       [0.17451181, 0.18312895, 0.25170427]])

In [215]:

mat2 = np.random.rand(3, 3)
mat2

array([[0.08553343, 0.05379513, 0.3803223 ],
       [0.53373599, 0.73058774, 0.41759968],
       [0.43602059, 0.33551301, 0.07459149]])

In [216]:
result = np.dot(mat1, mat2)
result

array([[0.47170822, 0.41802975, 0.46449634],
       [0.8385721 , 0.95561277, 0.47093812],
       [0.22241735, 0.22762971, 0.16162032]])

In [217]:
#Q65
arr = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)
percentile_90 = np.percentile(arr, 90)
first_quartile = np.percentile(arr, 25)
third_quartile = np.percentile(arr, 75)


In [218]:
print(percentile_10)

151.9


In [219]:

print(percentile_50)  #also median

486.0


In [220]:

print(percentile_90)

893.4000000000001


In [221]:

print(first_quartile)

283.5


In [222]:

print(third_quartile)

728.75


In [223]:
#Q66
arr = np.random.randint(1, 101, size=10)
arr

array([80, 33, 93,  9, 29, 75, 96, 87,  3, 71])

In [224]:
to_find = 71
index = np.where(arr == to_find)
index


(array([9]),)

In [225]:
#Q67
arr = np.random.randint(1, 101, size=25)
sorted_arr = np.sort(arr)
sorted_arr

array([  5,   5,   8,  12,  12,  12,  33,  33,  35,  39,  41,  47,  59,
        61,  69,  70,  72,  74,  78,  86,  88,  89,  97,  99, 100])

In [226]:
#Q68
arr = np.array([12, 25, 6, 42, 8, 30])
arr1 = arr[arr > 20]
arr1


array([25, 42, 30])

In [227]:
#Q69
arr = np.array([1, 5, 8, 12, 15])
arr2 = arr[arr % 3 == 0]
arr2

array([12, 15])

In [228]:
#Q70
arr = np.array([10, 20, 30, 40, 50])
arr2 = arr[(arr >= 20) & (arr <= 40)]
arr2

array([20, 30, 40])

In [229]:
#Q71
arr = np.array([1, 2, 3])
b_order = arr.dtype.byteorder
b_order

'='

In [230]:
#Q72
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

array([16777216, 33554432, 50331648], dtype=int32)

In [232]:
#Q73
arr = np.array([1, 2, 3], dtype=np.int32)
arr2 = arr.newbyteorder()
arr2

array([16777216, 33554432, 50331648], dtype='>i4')

In [233]:
#Q76
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100

In [234]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [235]:
copy_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [237]:
#Q77
matrix = np.random.randint(0, 10, size=(3, 3))
matrix

array([[9, 4, 4],
       [7, 2, 7],
       [2, 0, 9]])

In [238]:
view_slice = matrix[1:3, 1:3]
view_slice[0, 0] = 21
view_slice

array([[21,  7],
       [ 0,  9]])

In [239]:
matrix

array([[ 9,  4,  4],
       [ 7, 21,  7],
       [ 2,  0,  9]])

In [242]:
#Q78
array_a = np.arange(1, 13).reshape(4, 3)
array_a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [243]:
view_b = array_a[1:3, 1:3]
view_b += 5
view_b

array([[10, 11],
       [13, 14]])

In [244]:
array_a

array([[ 1,  2,  3],
       [ 4, 10, 11],
       [ 7, 13, 14],
       [10, 11, 12]])

In [249]:
#Q79
orig_array = np.arange(1, 9).reshape(2, 4)
orig_array


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [250]:
reshaped_view = orig_array.reshape(4, 2)

reshaped_view

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [251]:
reshaped_view[1, 0] = 12

In [253]:
orig_array

array([[ 1,  2, 12,  4],
       [ 5,  6,  7,  8]])

In [254]:
#Q80
data = np.random.randint(1, 10, size=(3, 4))


In [255]:
data

array([[5, 5, 4, 7],
       [9, 7, 8, 4],
       [3, 9, 7, 1]])

In [256]:
data_copy = data[data > 5].copy()
data_copy

array([7, 9, 7, 8, 9, 7])

In [257]:
data_copy[0] = 99

In [258]:
data_copy

array([99,  9,  7,  8,  9,  7])

In [259]:
data

array([[5, 5, 4, 7],
       [9, 7, 8, 4],
       [3, 9, 7, 1]])

In [260]:
#Q81
A = np.array([[1, 5, 3], [4, 1, 7], [7, 2, 9]])
B = np.array([[9, 8, 8], [6, 3, 4], [4, 1, 1]])
add_result = A + B
sub_result = A - B

In [261]:
add_result

array([[10, 13, 11],
       [10,  4, 11],
       [11,  3, 10]])

In [262]:
sub_result

array([[-8, -3, -5],
       [-2, -2,  3],
       [ 3,  1,  8]])

In [264]:
#Q82
C = np.random.randint(1, 10, size=(3, 2))
C

array([[8, 6],
       [8, 6],
       [3, 8]])

In [265]:

D = np.random.randint(1, 10, size=(2, 4))
D

array([[5, 2, 3, 8],
       [5, 4, 4, 5]])

In [266]:
np.dot(C, D)

array([[70, 40, 48, 94],
       [70, 40, 48, 94],
       [55, 38, 41, 64]])

In [267]:
#Q83
E = np.random.randint(1, 10, size=(4, 3))
E

array([[3, 9, 6],
       [2, 9, 6],
       [3, 2, 8],
       [3, 4, 4]])

In [268]:

E_t = E.T


In [269]:
E_t

array([[3, 2, 3, 3],
       [9, 9, 2, 4],
       [6, 6, 8, 4]])

In [270]:
#Q84
F = np.random.randint(1, 10, size=(4, 4))
F


array([[7, 8, 2, 6],
       [3, 4, 8, 5],
       [4, 9, 1, 7],
       [1, 8, 8, 8]])

In [271]:
np.linalg.det(F)


126.00000000000033

In [272]:
#Q85
G = np.random.randint(1, 10, size=(3, 3))
G


array([[4, 5, 9],
       [5, 7, 7],
       [9, 8, 3]])

In [273]:
G_inv = np.linalg.inv(G)
G_inv

array([[ 0.3271028 , -0.53271028,  0.26168224],
       [-0.44859813,  0.64485981, -0.1588785 ],
       [ 0.21495327, -0.12149533, -0.02803738]])